server:
  address: 0.0.0.0    # 모든 NIC 바인딩
  port: ${PORT:8080}          # 서비스 포트

spring:
  profiles:
    active: h2     # 기본 활성 프로필
  config:
    import: "optional:classpath:/application-secrets.yml"   # 비밀값 분리
  servlet:
    multipart:
      max-file-size: 50MB     # 단일 파일 최대 크기
      max-request-size: 50MB  # 요청 전체 최대 크기

  # ① 기본(프라이머리) DataSource: MSSQL — 계정은 secrets로 분리
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://10.131.121.110:1433;databaseName=SMLF_MST;encrypt=true;trustServerCertificate=true

asboard:
  file:
    public-base: /upload                        # 정적 공개 URL 프리픽스
    upload-root: ${ASBOARD_FILE_UPLOAD_ROOT:}   # 환경변수로 덮어쓰기(없으면 각 프로필 yml 값 사용)

mybatis:
  mapper-locations: classpath:/mapper/h2/**/*.xml  # 매퍼 XML 위치
  type-aliases-package: com.inpro.asBoard       # 타입 alias 패키지
  configuration:
    map-underscore-to-camel-case: true          # 컬럼 스네이크 → 카멜 매핑
    # jdbc-type-for-null: 'NULL'                # 필요 시 활성화