# [local] 로컬 개발 프로필 전용: 업로드 루트 경로 설정
spring:
  config:
    activate:
      on-profile: dev
  # ① 기본(프라이머리) DataSource: MSSQL — 계정은 secrets로 분리
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.131.121.110:1433;databaseName=SMLF_MST;encrypt=true;trustServerCertificate=true

mybatis:
  mapper-locations: classpath:/mapper/ms/**/*.xml  # 매퍼 XML 위치

asboard:
  file:
    # Windows 경로는 따옴표 + 슬래시(/) 권장
    upload-root: "D:/999_AS/src/main/resources/static/upload"
